config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  constraints(Subdomain) do
    get '/' => 'groups#show'
  end

  root :to => "pages#index"

  resources :menus do 
    resources :templates
  end
end

app/models/archive.rb
class Archive < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_memberships
  has_many :items, :through => :category_memberships
  has_many :subcategories
  belongs_to :section
  liquid_methods :subcategories, :items, :name
end

app/models/category_membership.rb
class CategoryMembership < ActiveRecord::Base
  belongs_to :item
  belongs_to :category
end

app/models/group.rb
class Group < ActiveRecord::Base
  validates_format_of :name, with: /\A([^@\s]+)/, message: "must be lowercase alphanumerics only"
  validates_length_of :name, maximum: 32, message: "exceeds maximum of 32 characters"
  validates_exclusion_of :name, in: ['www', 'mail', 'ftp'], message: "is not available"
  validates :subdomain, uniqueness: true
  has_many :memberships
  has_many :users, :through => :memberships
  has_many :menus
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :category_memberships
  has_many :categories, :through => :category_memberships
  has_many :subcategory_memberships
  has_many :subcategories, :through => :subcategory_memberships
  liquid_methods :text
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  belongs_to :group
  has_many :templates
  liquid_methods :categories,  :name
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :menu
  has_many :categories
  liquid_methods :categories, :position
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
  has_many :subcategory_memberships
  has_many :items, :through => :subcategory_memberships

  liquid_methods :items, :name
end

app/models/template.rb
class Template < ActiveRecord::Base
  has_many :sections
  belongs_to :menu
  liquid_methods :sections
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :memberships
  has_many :groups, :through => :memberships
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Menustyler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
  <section class="container">
    <%= yield %>    
  </section>
</body>
</html>

app/views/pages/index.html.erb
Here is where groups are created


<div class="fixed-action-btn horizontal" style="bottom: 45px; right: 24px;">
  <a class="btn-floating btn-large red">
    <i class="large material-icons">mode_edit</i>
  </a>
  <ul>
    <li><a class="btn-floating red"><i class="material-icons">insert_chart</i></a></li>
    <li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
    <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
    <li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
  </ul>
</div>

app/views/templates/index.html.erb
<h1>This menu has the following templates:</h1>

<% @templates.each do |template| %>
    <h1><%= link_to template.name, menu_templates_path(@menu, template) %></h1>
    <p><%= template.description %></p>
<% end %>

app/views/templates/partials/_show.html.erb
<%= Liquid::Template.parse(template).render('categories' => categories).html_safe %>

app/views/templates/show.html.erb
<%= @template %>
<%= Liquid::Template.parse(@template.structure).render({'sections' => @template.sections}).html_safe %>